### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 06065044** [r9ronaldozhang/ZYColumnViewController#12]
请问能不能快速修改为所有的栏目都可以删除和排序，不保留固定的一个？

**Comment by r9ronaldozhang** [comment]
创建控制器后将控制器open属性 fixedCount = 0 自行测试是否存在bug

**Comment by 06065044** [comment]
目前来看，存在着较大的问题，改起来也没啥头绪

**Comment by r9ronaldozhang** [comment]
设计之初默认就是保证了必须保留一个固定的，如果不合适，可以选择其他，谢谢

**Comment by 06065044** [comment]
已经修改完毕了，效果还是不错的，赞一个
