### ISSUE TITLE
如果我隐藏导航栏呢?

### ISSUE THREAD

**Issue by Joanlove526** [r9ronaldozhang/ZYColumnViewController#6]
我的项目中又导航栏, 但是由于是首页, 所以我隐藏了导航栏,导致出错了, view的位置不对

**Comment by Joanlove526** [comment]
怎么解决啊

**Comment by r9ronaldozhang** [comment]
隐藏导航栏不会有影响，只是这个空间，默认是放在导航栏下面的。我的实际使用项目Y值也并非是64高度。而是包装了其他父控件，没有问题。至于你项目具体是怎样的UI需求，不太清楚
